[package]
name = "Shirley"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
agent-sdk = { version = "0.1.0", path = "./crates/agent-sdk" }
syn = { version = "3.0.6", features = ["full"] }
proc-macro2 = "1.0.107"
quote = "1.0.47"
schemars = { version = "1.2.2", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt", "process", "time"] }
dotenvy = "0.15.7"
futures = "0.3.34"
chrono = "0.4.45"

[workspace]
members = [
    "crates/agent-sdk",
    "crates/agent-sdk-macros",
]
resolver = "3"
